version: "3"

vars:
  APP_NAME: x1ctl
  FAKE_APP_NAME: fakeprinter
  DIST_DIR: dist
  VERSION:
    sh: git describe --tags --always --dirty
  LD_FLAGS: '-X github.com/joeblew999/3d-printers/internal/version.Version={{.VERSION}}'
  SITE_DIR: .site

tasks:
  default:
    desc: Build binaries for common OS/ARCH targets
    cmds:
      - task: build:all

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.DIST_DIR}}

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  build:
    desc: Build binary for a specific OS/ARCH (defaults to host). Override NAME for other cmds.
    vars:
      OS: '{{.OS | default .GOOS}}'
      ARCH: '{{.ARCH | default .GOARCH}}'
      EXT: '{{if eq .OS "windows"}}.exe{{end}}'
      NAME: '{{.NAME | default .APP_NAME}}'
    cmds:
      - mkdir -p {{.DIST_DIR}}
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build -ldflags "{{.LD_FLAGS}}" -o {{.DIST_DIR}}/{{.NAME}}_{{.OS}}_{{.ARCH}}{{.EXT}} ./cmd/{{.NAME}}

  build:x1ctl:
    desc: Build x1ctl for a specific OS/ARCH (defaults to host)
    cmds:
      - task: build
        vars:
          NAME: '{{.APP_NAME}}'
          OS: '{{.OS | default .GOOS}}'
          ARCH: '{{.ARCH | default .GOARCH}}'

  build:fakeprinter:
    desc: Build fakeprinter for a specific OS/ARCH (defaults to host)
    cmds:
      - task: build
        vars:
          NAME: '{{.FAKE_APP_NAME}}'
          OS: '{{.OS | default .GOOS}}'
          ARCH: '{{.ARCH | default .GOARCH}}'

  build:all:
    desc: Build binaries for standard OS/ARCH matrix (linux/windows/darwin × amd64/arm64)
    cmds:
      - task: build:x1ctl
        vars: {OS: linux, ARCH: amd64}
      - task: build:x1ctl
        vars: {OS: linux, ARCH: arm64}
      - task: build:x1ctl
        vars: {OS: darwin, ARCH: amd64}
      - task: build:x1ctl
        vars: {OS: darwin, ARCH: arm64}
      - task: build:x1ctl
        vars: {OS: windows, ARCH: amd64}
      - task: build:x1ctl
        vars: {OS: windows, ARCH: arm64}
      - task: build:fakeprinter
        vars: {OS: linux, ARCH: amd64}
      - task: build:fakeprinter
        vars: {OS: linux, ARCH: arm64}
      - task: build:fakeprinter
        vars: {OS: darwin, ARCH: amd64}
      - task: build:fakeprinter
        vars: {OS: darwin, ARCH: arm64}
      - task: build:fakeprinter
        vars: {OS: windows, ARCH: amd64}
      - task: build:fakeprinter
        vars: {OS: windows, ARCH: arm64}

  ci:
    desc: Run tests and build all targets
    cmds:
      - task: test
      - task: build:all

  tag:
    desc: "Create and push a version tag (usage: task tag VERSION=v0.1.0)"
    requires:
      vars: [VERSION]
    cmds:
      - git tag {{.VERSION}}
      - git push origin {{.VERSION}}

  version:
    desc: Show the resolved version (git describe)
    cmds:
      - echo {{.VERSION}}

  serve:
    desc: Serve docs locally on :8080
    cmds:
      - go run ./cmd/site -dir docs -addr :8080

  docs:build:
    desc: Render docs markdown to static HTML in {{.SITE_DIR}}
    cmds:
      - go run ./cmd/sitebuild -src docs -out {{.SITE_DIR}}

  fakeprinter:
    desc: Run a local fake printer (TLS websocket on :8883)
    cmds:
      - go run ./cmd/fakeprinter -addr :8883
